In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr_2d=np.array([[5,10,15],[20,40,59],[1,56,28]])

In [7]:
arr_2d

array([[ 5, 10, 15],
       [20, 40, 59],
       [ 1, 56, 28]])

In [8]:
arr_2d[0][0]

5

In [9]:
arr_2d[0]

array([ 5, 10, 15])

In [12]:
arr_2d[2,2]

28

In [ ]:
arr_2d[:2,1:]