In [3]:
my_list=[1,2,3]
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3])

In [4]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [11]:
np.ones((5,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [13]:
np.linspace(0,5,100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [14]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
np.random.rand(5)

array([ 0.26504937,  0.54067026,  0.83295341,  0.44037121,  0.38935626])

In [16]:
np.random.rand(5,5)

array([[ 0.4783913 ,  0.58356296,  0.34439178,  0.95544054,  0.99917824],
       [ 0.14000959,  0.52403353,  0.68164801,  0.23182879,  0.62775477],
       [ 0.5639037 ,  0.07405284,  0.99838915,  0.03391922,  0.06725844],
       [ 0.38888974,  0.94159169,  0.56372693,  0.07492164,  0.5114994 ],
       [ 0.91667713,  0.77296446,  0.76997554,  0.9964492 ,  0.32512491]])

In [17]:
np.random.randn(2)

array([-0.47209912, -0.48065574])

In [18]:
np.random.randn(5,5)

array([[ 1.28828616,  1.6810421 ,  0.65962395, -1.40494727,  1.04732633],
       [ 1.64493885,  0.24654023, -0.55491297, -0.39539707,  2.8580094 ],
       [-0.75186275,  2.38339408,  0.43014267,  1.99663948,  0.69931449],
       [ 1.06990152, -1.25119977,  0.50284685, -0.57204348,  0.20228245],
       [ 1.17288331,  0.50834625,  0.26787818, -0.24622434,  0.1159774 ]])

In [19]:
np.random.randint(0,100)

9

In [21]:
np.random.randint(1,100,100)

array([31, 58,  5, 95, 85, 65, 34, 93, 90, 25, 17, 88, 66, 60, 73, 49,  8,
       28,  9, 42, 97, 40, 28, 13, 80,  6, 95, 34, 18, 22, 61, 52, 59, 92,
       19, 28, 57, 81, 85, 80, 87, 69, 75, 34, 62,  2, 31, 25, 90, 29, 34,
       32, 69,  5, 22, 86, 45, 86,  7, 24,  8, 99, 72, 10, 47, 61, 32, 30,
       25, 92, 26, 44, 41, 39, 43, 47, 37,  8, 90, 82, 36, 72, 80, 57, 15,
       10, 46, 99, 64, 39, 72, 74, 68, 20, 32,  3,  2, 69, 24, 71])

In [22]:
np.random.randint(1,100,10)

array([17, 31, 83, 99, 31, 79, 88,  8, 93, 23])

In [24]:
ranarr = np.random.randint(0,50,10)

In [25]:
ranarr

array([32, 47,  4, 34,  7,  4, 42, 28, 22, 42])

In [29]:
ranarr.reshape(5,2)

array([[32, 47],
       [ 4, 34],
       [ 7,  4],
       [42, 28],
       [22, 42]])

In [30]:
ranarr

array([32, 47,  4, 34,  7,  4, 42, 28, 22, 42])

In [31]:
ranarr.max()

47

In [32]:
ranarr.min()

4

In [33]:
ranarr.argmax()

1

In [34]:
ranarr.argmin()

2

In [36]:
ranarr.shape

(10,)

In [38]:
ranarr_reshaped=ranarr.reshape(2,5)

In [39]:
ranarr_reshaped

array([[32, 47,  4, 34,  7],
       [ 4, 42, 28, 22, 42]])

In [40]:
ranarr_reshaped.shape

(2, 5)